import './globals.css'
import {ClusterProvider} from '@/components/cluster/cluster-data-access'
import {SolanaProvider} from '@/components/solana/solana-provider'
import {UiLayout} from '@/components/ui/ui-layout'
import {ReactQueryProvider} from './react-query-provider'
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { getServerSession } from 'next-auth/next'
import AuthProvider from './AuthProvider'


export const metadata = {
  title: 'coatcheck',
  description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
  { label: 'Coat Check', path: '/coatcheck/dashboard' },
]


export default async  function RootLayout({ children }: { children: React.ReactNode}) {

  const session = await getServerSession()

  return (
    <html lang="en">
      <body>
        <AuthProvider >
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <UiLayout links={links}>{children}</UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
        <ToastContainer />
        </AuthProvider>
      </body>
    </html>
  )
}

